---
mgmt_gateway: 172.16.1.1

# Spine switch group
spine:
  defaults:
    platform: ceos
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # Pool of IPv6 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv6_pool: fc00:dead:beef:255::/64
    bgp_as: 65100

  nodes:
    - name: dc1-spine1
      id: 1
      mgmt_ip: 172.16.1.11/24
    - name: dc1-spine2
      id: 2
      mgmt_ip: 172.16.1.12/24
    - name: dc1-spine3
      id: 3
      mgmt_ip: 172.16.1.13/24

# L3 Leaf switch group
l3leaf:
  defaults:
    platform: ceos
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # Pool of IPv6 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv6_pool: fc00:dead:beef:255::/64
    # Offset all assigned loopback IP addresses.
    # Required when the < loopback_ipv4_pool > is same for 2 different node_types (like spine and l3leaf) to avoid over-lapping IPs.
    # For example, set the minimum offset l3leaf.defaults.loopback_ipv4_offset: < total # spine switches > or vice versa.
    loopback_ipv4_offset: 3
    loopback_ipv6_offset: 3
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 10.255.1.0/27
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: ['dc1-spine1', 'dc1-spine2', 'dc1-spine3']
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 10.255.255.0/26
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.255.1.64/27
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.255.1.96/27
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

  node_groups:
    - group: RACK1
      bgp_as: 65101
      filter:
        tags: [ "RACK1" ]
      nodes:
        - name: dc1-leaf1a
          id: 1
          mgmt_ip: 172.16.1.101/24
          uplink_switch_interfaces:
            - Ethernet1
            - Ethernet1
            - Ethernet1
        - name: dc1-leaf1b
          id: 2
          mgmt_ip: 172.16.1.102/24
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2
            - Ethernet2

    - group: RACK2
      filter:
        tags: [ "RACK2" ]
      bgp_as: 65102
      nodes:
        - name: dc1-leaf2a
          id: 3
          mgmt_ip: 172.16.1.103/24
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3
            - Ethernet3
        - name: dc1-leaf2b
          id: 4
          mgmt_ip: 172.16.1.104/24
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4
            - Ethernet4

host:
  defaults:
    platform: ceos
    loopback_ipv4_pool: 10.255.255.0/27
    bgp_as: 65000
    spanning_tree_mode: mstp
  node_groups:
    - group: HOSTS-RACK1
      uplink_switches: ['dc1-leaf1a', 'dc1-leaf1b']
      nodes:
        - name: host1a
          id: 1
          mgmt_ip: 172.16.1.121/24
          uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
        - name: host1b
          id: 1
          mgmt_ip: 172.16.1.122/24
          uplink_switch_interfaces:
            - Ethernet8
            - Ethernet8

    - group: HOSTS-RACK2
      uplink_switches: ['dc1-leaf2a', 'dc1-leaf2b']
      nodes:
        - name: host2a
          id: 2
          mgmt_ip: 172.16.1.123/24
          uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
        - name: host2b
          id: 2
          mgmt_ip: 172.16.1.124/24
          uplink_switch_interfaces:
            - Ethernet8
            - Ethernet8
